Repository dbt-labs/dbt-redshift, pull requests merged in 2022-12, with the labels that each got.

#232 1.1.latest backport of tox 4.0.0 passenv fixes
  tox.ini
Labels: cla:yes, Skip Changelog

#230 Make tox.ini conform to 4.0.0 release requirements
  Makefile
  tests/unit/test_context.py
  tests/unit/utils.py
  tox.ini
Labels: cla:yes, Skip Changelog

#239 add release workflow
  .github/workflows/release.yml
Labels: Skip Changelog

#241 Fix changelog footer, update contributor list
  .changes/0.0.0.md
  .changie.yaml
Labels: cla:yes, Skip Changelog

#243 fix trigger
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#244 Pin full commit sha
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#245 update needs
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#236 CT-1524 - Add support for python 3.11
  .changes/unreleased/Dependencies-20221209-233905.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  Makefile
  dev-requirements.txt
  setup.py
  tests/conftest.py
  tests/functional/adapter/test_basic.py
  tests/test_incremental_run_result.py
  tests/unit/mock_adapter.py
  tests/unit/test_context.py
  tests/unit/test_redshift_adapter.py
  tests/unit/utils.py
  tox.ini
Labels: cla:yes

#253 Consistent capitalization for `CONTRIBUTING.md`
  .changes/unreleased/Under the Hood-20221219-163610.yaml
  .github/workflows/changelog-existence.yml
  CONTRIBUTING.md
Labels: cla:yes, ready_for_review
