Repository dbt-labs/dbt-redshift, pull requests merged in 2022-09, with the labels that each got.

#186 ignore adapter MyPy issues
  .changes/unreleased/Under the Hood-20220913-143919.yaml
  dbt/adapters/redshift/__init__.py
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/impl.py
Labels: cla:yes

#176 Update repo templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/ISSUE_TEMPLATE/release.md
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#190 add type boolean
  .changes/unreleased/Features-20220919-235003.yaml
  tests/functional/adapter/utils/test_data_types.py
Labels: cla:yes, ready_for_review

#192 Tests for `current_timestamp`
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, Skip Changelog

#182 Array macros
  .changes/unreleased/Features-20220912-223245.yaml
  dbt/include/redshift/macros/utils/array_append.sql
  dbt/include/redshift/macros/utils/array_concat.sql
  dbt/include/redshift/macros/utils/array_construct.sql
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, ready_for_review

#191 consolidate timestamps
  .changes/unreleased/Under the Hood-20220926-101606.yaml
  dbt/include/redshift/macros/adapters.sql
  dbt/include/redshift/macros/timestamps.sql
  tests/functional/adapter/utils/test_timestamps.py
Labels: cla:yes
