Repository dbt-labs/dbt-redshift, pull requests merged in 2023-09, with the labels that each got.

#598 [ADAP-878] update expected values
  .changes/unreleased/Fixes-20230908-113019.yaml
  tests/functional/adapter/expected_stats.py
Labels: cla:yes

#602 Fix replace sql macro
  .changes/unreleased/Fixes-20230912-133327.yaml
  dbt/include/redshift/macros/relations/materialized_view/alter.sql
  tests/functional/adapter/materialized_view_tests/utils.py
Labels: cla:yes

#603 add relation macros and add relation renameable/replaceable config
  .changes/unreleased/Fixes-20230912-133327.yaml
  dbt/adapters/redshift/relation.py
  dbt/include/redshift/macros/materializations/table.sql
  dbt/include/redshift/macros/materializations/view.sql
  dbt/include/redshift/macros/relations/drop.sql
  dbt/include/redshift/macros/relations/materialized_view/_replace.sql
  dbt/include/redshift/macros/relations/table/drop.sql
  dbt/include/redshift/macros/relations/table/rename.sql
  dbt/include/redshift/macros/relations/view/drop.sql
  dbt/include/redshift/macros/relations/view/rename.sql
  dbt/include/redshift/macros/relations/view/replace.sql
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
Labels: cla:yes

#604 allow for bool/str input to backup/autorefresh when configuring materialized views
  .changes/unreleased/Under the Hood-20230914-135547.yaml
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/utility.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/unit/relation_configs/test_materialized_view.py
Labels: cla:yes

#607 Update Fixes-20230912-133327.yaml
  .changes/unreleased/Fixes-20230912-133327.yaml
Labels: cla:yes, Skip Changelog

#608 Update Under the Hood-20230914-135547.yaml
  .changes/unreleased/Under the Hood-20230914-135547.yaml
Labels: cla:yes

#612 Avoid nested loop in query planner execution
  .changes/unreleased/Fixes-20230923-091155.yaml
  dbt/include/redshift/macros/relations.sql
Labels: cla:yes, ready_for_review, ok to test

#618 automate repo cleanup
  .github/workflows/repository-cleanup.yml
Labels: cla:yes, Skip Changelog

#617 Add tests for `date_spine` macro, and sub macros
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, Skip Changelog

#611 add dbt show tests
  .changes/unreleased/Under the Hood-20230925-150132.yaml
  tests/functional/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest
