Repository dbt-labs/dbt-redshift, pull requests merged in 2023-05, with the labels that each got.

#418 update used gh actions ahead of set-output, node12 deprecation
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#435 Fix execute signature based on core
  .changes/unreleased/Fixes-20230509-143721.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes

#450 updating set-output
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#444 [Backport] 1.1.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#448 [Backport] 1.2.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#445 [Backport] 1.3.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#446 [Backport] 1.4.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#447 [Backport] 1.5.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#453 update used gh actions ahead of node12 deprecation
  .github/workflows/backport.yml
  .github/workflows/bot-changelog.yml
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#458 Add autocommit feature to let dbt users run certain db commands in macros
  .changes/unreleased/Fixes-20230520-043039.yaml
  dbt/adapters/redshift/connections.py
  tests/functional/adapter/test_autocommit.py
Labels: cla:yes, backport 1.5.latest

#433 Default connect_timeout to None
  .changes/unreleased/Fixes-20230508-094834.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes, ready_for_review, backport 1.5.latest, pr_tracked

#464 [backport] Add autocommit feature to let dbt users run certain db commands in macros
  .changes/unreleased/Fixes-20230520-043039.yaml
  dbt/adapters/redshift/connections.py
  tests/functional/adapter/test_autocommit.py
Labels: cla:yes

#465 [Backport] 433
  .changes/unreleased/Fixes-20230508-094834.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes

#466 Escape `%` symbols in table/view/column comments
  .changes/unreleased/Fixes-20230524-151825.yaml
  dbt/include/redshift/macros/adapters.sql
Labels: cla:yes, ready_for_review, pr_tracked

#468 Use smaller batch size for seeds
  .changes/unreleased/Fixes-20230524-165236.yaml
  dbt/include/redshift/macros/materializations/seeds/helpers.sql
Labels: cla:yes, ready_for_review, pr_tracked

#459 convert to reusable nightly tests
  .github/workflows/integration.yml
  .github/workflows/release-branch-tests.yml
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#474 drop support for py37
  .changes/unreleased/Breaking Changes-20230530-165542.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes

#473 ADAP-512: sslmode translation
  .changes/unreleased/Breaking Changes-20230522-111945.yaml
  .changes/unreleased/Fixes-20230512-082027.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes

#472 adding link to 1.5 release notes
  .changes/0.0.0.md
  CHANGELOG.md
Labels: cla:yes, Skip Changelog
