Repository dbt-labs/dbt-redshift, pull requests merged in 2023-10, with the labels that each got.

#614 ADAP-891: Support test results as views
  .changes/unreleased/Features-20230921-153707.yaml
  tests/functional/adapter/test_store_test_failures.py
Labels: cla:yes

#568 Use the PID to terminate the session
  .changes/unreleased/Fixes-20230807-174409.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes, ready_for_review

#635 add docs-issue workflow to dbt-redshift
  .github/workflows/docs-issues.yml
Labels: cla:yes, Skip Changelog

#601 Update redshift-connector requirement from 2.0.913 to 2.0.915
  .changes/unreleased/Dependencies-20230912-120620.yaml
  setup.py
Labels: cla:yes, ok to test

#645 [Backport 1.6.latest] Fix parsing of database results for materialized view autorefresh
  .changes/unreleased/Fixes-20231025-203732.yaml
  dbt/adapters/redshift/relation_configs/materialized_view.py
Labels: cla:yes

#640 backport 601 to 1.6.latest
  .changes/unreleased/Dependencies-20230912-120620.yaml
  setup.py
Labels: cla:yes

#639 backport 601 to 1.7.latest
  .changes/unreleased/Dependencies-20230912-120620.yaml
  setup.py
Labels: cla:yes

#650 allow user to set debug level via env var
  .changes/unreleased/Features-20231030-101055.yaml
  dbt/adapters/redshift/impl.py
Labels: cla:yes
