Repository dbt-labs/dbt-redshift, pull requests merged in 2023-07, with the labels that each got.

#513 [Backport 1.3.latest] Dropping support for py37
  .changes/unreleased/Breaking Changes-20230530-165542.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  CONTRIBUTING.MD
  setup.py
  tox.ini
Labels: cla:yes

#514 [Backport 1.2.latest] Dropping support for py37
  .changes/unreleased/Breaking Changes-20230530-165542.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  CONTRIBUTING.MD
  setup.py
  tox.ini
Labels: cla:yes

#512 [Backport 1.1.latest] Dropping support for py37
  .changes/unreleased/Breaking Changes-20230530-165542.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.MD
  setup.py
  tox.ini
Labels: cla:yes

#510 [Backport 1.0.latest] Dropping support for py37
  .changes/unreleased/Breaking Changes-20230530-165542.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.MD
  setup.py
  tox.ini
Labels: cla:yes

#519 exclude redshift-connector==2.0.912
  .changes/unreleased/Fixes-20230706-001056.yaml
  setup.py
Labels: cla:yes, backport 1.5.latest

#522 exclude redshift-connector==2.0.912
  .changes/unreleased/Fixes-20230706-001056.yaml
  setup.py
Labels: cla:yes

#520 Add new `defer_relation` argument to `mock_model`
  .changes/unreleased/Fixes-20230706-001056.yaml
  .changes/unreleased/Fixes-20230706-012233.yaml
  setup.py
  tests/unit/test_context.py
Labels: cla:yes

#523 cast port as integer
  .changes/unreleased/Fixes-20230706-123329.yaml
  dbt/adapters/redshift/connections.py
  setup.py
Labels: cla:yes, test all

#528 fix whitespace change
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#428 Override list_relations_without_caching
  .changes/unreleased/Features-20230407-104723.yaml
  dbt/adapters/redshift/__init__.py
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/adapters.sql
  tests/functional/adapter/test_adapter_methods.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes, test all, ok to test

#530 hard pin to latest compatible version
  .changes/unreleased/Fixes-20230713-105351.yaml
  setup.py
Labels: cla:yes

#533 [BACKPORT] cast port as integer (#523)
  .changes/unreleased/Fixes-20230706-123329.yaml
  dbt/adapters/redshift/connections.py
  setup.py
Labels: cla:yes

#535 update changelog - this fix does not resolve 217 and 17
  .changes/unreleased/Features-20230407-104723.yaml
Labels: cla:yes, Skip Changelog

#534 [BACKPORT] manual backport of pr 530
  .changes/unreleased/Fixes-20230713-105351.yaml
  setup.py
Labels: cla:yes

#537 add query commenting back
  .changes/unreleased/Fixes-20230713-190412.yaml
  dbt/adapters/redshift/connections.py
Labels: cla:yes, ok to test

#490 add merge as a valid incremental strategy
  .changes/unreleased/Features-20230613-144752.yaml
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/materializations/incremental_merge.sql
  tests/functional/adapter/incremental/test_incremental_merge_exclude_columns.py
  tests/functional/adapter/incremental/test_incremental_predicates.py
  tests/functional/adapter/incremental/test_incremental_run_result.py
  tests/functional/adapter/incremental/test_incremental_strategies.py
  tests/functional/adapter/incremental/test_incremental_unique_id.py
Labels: cla:yes, ready_for_review, ok to test

#540 Apply new integration tests to existing framework to identify supported features
  .changes/unreleased/Features-20230714-160100.yaml
  Makefile
  dbt/adapters/redshift/impl.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/include/redshift/macros/materializations/materialized_view.sql
  tests/functional/adapter/materialized_view_tests/fixtures.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/functional/adapter/materialized_view_tests/utils.py
Labels: cla:yes

#539 add datadog env vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#545 [Backport 1.4.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#544 [Backport 1.3.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#543 [Backport 1.2.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#547 [Backport 1.6.latest] Add Datadog Env Vars
  .github/workflows/integration.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#552 Update stale workflow to use the centralized version
  .changes/unreleased/Under the Hood-20230724-164439.yaml
  .github/workflows/stale.yml
Labels: cla:yes
