Repository dbt-labs/dbt-redshift, pull requests merged in 2023-11, with the labels that each got.

#653 ADAP-973: Fix issue where materialized views were being mapped as views in catalog queries
  .changes/unreleased/Fixes-20231030-234315.yaml
  dbt/include/redshift/macros/catalog.sql
  tests/functional/adapter/catalog_tests/files.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
Labels: cla:yes, backport 1.6.latest, backport 1.7.latest

#657 ADAP-923: Resolve issue where backup parameter was inadvertently considered in configuration change monitoring
  .changes/unreleased/Fixes-20231103-181357.yaml
  dbt/adapters/redshift/relation.py
  dbt/adapters/redshift/relation_configs/__init__.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
Labels: cla:yes, backport 1.6.latest, backport 1.7.latest

#647 Fixes #641 by using the svv_mv_info view which is queryable
  .changes/unreleased/Fixes-20231026-164623.yaml
  dbt/include/redshift/macros/relations/materialized_view/describe.sql
Labels: cla:yes, ready_for_review, ok to test

#674 Fix #624 by removing unnecessary boto3 version peg
  .changes/unreleased/Dependencies-20231130-044332.yaml
  setup.py
  tests/functional/adapter/test_basic.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes, ok to test, support

#677 Backport #674 to 1.6.latest
  .changes/unreleased/Dependencies-20231130-044332.yaml
  setup.py
  tests/functional/adapter/test_basic.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes
