Repository dbt-labs/dbt-redshift, pull requests merged in 2023-08, with the labels that each got.

#525 Move Alerts
  .github/workflows/integration.yml
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#569 ADAP-761: Add retry logic to flaky MV tests to avoid "cannot open relation with OID" error
  .changes/unreleased/Under the Hood-20230808-141645.yaml
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/functional/adapter/materialized_view_tests/utils.py
Labels: cla:yes, backport 1.6.latest

#574 ADAP-761: [backport] Add retry logic to flaky MV tests to avoid "cannot open relation with OID" error
  .changes/unreleased/Under the Hood-20230808-141645.yaml
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/functional/adapter/materialized_view_tests/utils.py
Labels: cla:yes

#576 ADAP-796: Add datadog env vars to tox.ini
  tox.ini
Labels: cla:yes, Skip Changelog

#582 ADAP-754: Split out integration tests to fit on the windows free tier
  tox.ini
Labels: cla:yes, Skip Changelog, backport 1.6.latest

#583 Auto-refresh on MVs not working as expected
  .changes/unreleased/Fixes-20230815-151655.yaml
  dbt/adapters/redshift/relation_configs/materialized_view.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
Labels: cla:yes, backport 1.6.latest

#592 Remove import of FieldEncoder from hologram
  .changes/unreleased/Fixes-20230830-164611.yaml
  dbt/adapters/redshift/connections.py
Labels: cla:yes

#590 ADAP-841: Reformat macro file structure to be more modular and organized
  .changes/unreleased/Under the Hood-20230829-113206.yaml
  dbt/include/redshift/macros/adapters.sql
  dbt/include/redshift/macros/materializations/materialized_view.sql
  dbt/include/redshift/macros/relations/drop.sql
  dbt/include/redshift/macros/relations/materialized_view/_replace.sql
  dbt/include/redshift/macros/relations/materialized_view/alter.sql
  dbt/include/redshift/macros/relations/materialized_view/create.sql
  dbt/include/redshift/macros/relations/materialized_view/describe.sql
  dbt/include/redshift/macros/relations/materialized_view/drop.sql
  dbt/include/redshift/macros/relations/materialized_view/refresh.sql
Labels: cla:yes
