Repository dbt-labs/dbt-redshift, pull requests merged in 2023-06, with the labels that each got.

#475 Restore transaction semantics used by dbt-redshift prior to 1.5
  .changes/unreleased/Fixes-20230531-153347.yaml
  dbt/adapters/redshift/connections.py
  tests/functional/adapter/test_autocommit.py
  tests/functional/test_autocommit.py
Labels: ok_to_test, cla:yes, test all, ok to test

#476 [backport] Restore transaction semantics used by dbt-redshift prior to 1.5 (#475)
  .changes/unreleased/Fixes-20230531-153347.yaml
  dbt/adapters/redshift/connections.py
  tests/functional/adapter/test_autocommit.py
  tests/functional/test_autocommit.py
Labels: cla:yes

#430 testing constraint rendering fixes
  .changes/unreleased/Under the Hood-20230511-162623.yaml
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#443 [Backport] 1.0.latest gh deprecations
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#478 Standardize the adapter for core debug changes.
  .changes/unreleased/Features-20230604-041410.yaml
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/impl.py
Labels: cla:yes

#482 re-pointing reelease branch env for nightly releases to a .latest branch
  .github/workflows/nightly-release.yml
Labels: cla:yes, Skip Changelog

#487 migrate redshift__list_relations_without_caching off postgres dependency
  .changes/unreleased/Fixes-20230608-180130.yaml
  dbt/include/redshift/macros/adapters.sql
Labels: cla:yes

#437 Test dbt-core#7537
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#485 Pass `region` param on to redshift conn as is
  .changes/unreleased/Fixes-20230612-114853.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes, backport 1.5.latest

#495 Revert "Escape `%` symbols in table/view/column comments (#466)"
  dbt/include/redshift/macros/adapters.sql
Labels: cla:yes, Skip Changelog, backport 1.5.latest

#493 increase minimum required version of `redshift_connector` driver
  .changes/unreleased/Breaking Changes-20230614-144743.yaml
  setup.py
Labels: cla:yes, backport 1.5.latest

#387 ADAP-389: Stub materialized view as a materialization
  dbt/adapters/redshift/relation.py
  dbt/adapters/redshift/relation_configs/__init__.py
  dbt/adapters/redshift/relation_configs/dist.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/sort.py
  dbt/include/redshift/macros/adapters.sql
  dbt/include/redshift/macros/materializations/materialized_view.sql
  dbt/include/redshift/macros/relations.sql
  dev-requirements.txt
  setup.py
  tests/functional/adapter/materialized_view_tests/fixtures.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/unit/utils.py
  tox.ini
Labels: cla:yes, Skip Changelog

#500 add dependent_projects_dict to utils.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#502 backport 474 to 1.5.latest
  .changes/unreleased/Breaking Changes-20230530-165542.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes

#394 ADAP-393: Add configuration change option
  dbt/adapters/redshift/__init__.py
  dbt/adapters/redshift/column.py
  dbt/adapters/redshift/impl.py
  dbt/adapters/redshift/relation.py
  dbt/adapters/redshift/relation_configs/__init__.py
  dbt/adapters/redshift/relation_configs/base.py
  dbt/adapters/redshift/relation_configs/dist.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/policies.py
  dbt/adapters/redshift/relation_configs/sort.py
  dbt/include/redshift/macros/materializations/materialized_view.sql
  dbt/include/redshift/macros/utils/dateadd.sql
  dbt/include/redshift/macros/utils/datediff.sql
  dbt/include/redshift/macros/utils/last_day.sql
  tests/functional/adapter/materialized_view_tests/fixtures.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
Labels: cla:yes, Skip Changelog

#386 ADAP-2: Materialized Views
  .changes/unreleased/Features-20230330-165842.yaml
  .flake8
  dbt/adapters/redshift/__init__.py
  dbt/adapters/redshift/column.py
  dbt/adapters/redshift/impl.py
  dbt/adapters/redshift/relation.py
  dbt/adapters/redshift/relation_configs/__init__.py
  dbt/adapters/redshift/relation_configs/base.py
  dbt/adapters/redshift/relation_configs/dist.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/policies.py
  dbt/adapters/redshift/relation_configs/sort.py
  dbt/include/redshift/macros/adapters.sql
  dbt/include/redshift/macros/materializations/materialized_view.sql
  dbt/include/redshift/macros/relations.sql
  dbt/include/redshift/macros/utils/dateadd.sql
  dbt/include/redshift/macros/utils/datediff.sql
  dbt/include/redshift/macros/utils/last_day.sql
  setup.py
  tests/functional/adapter/materialized_view_tests/fixtures.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tox.ini
Labels: cla:yes

#509 Remove dependent_projects argument from PartialProject call in unit tests
  .changes/unreleased/Fixes-20230628-123227.yaml
  tests/unit/utils.py
Labels: cla:yes

#515 fix release branch from recent backport
  .github/workflows/nightly-release.yml
Labels: cla:yes, Skip Changelog
