Repository dbt-labs/dbt-redshift, pull requests merged in 2023-04, with the labels that each got.

#397 Test conversion for simple snapshot into a functional test
  tests/functional/adapter/common.py
  tests/functional/adapter/snapshot_tests/seeds.py
  tests/functional/adapter/snapshot_tests/snapshots.py
  tests/functional/adapter/snapshot_tests/test_snapshot.py
  tests/functional/adapter/test_simple_snapshot.py
Labels: cla:yes, Skip Changelog

#395 Model-Level Constraints
  .changes/unreleased/Features-20230406-104634.yaml
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/adapters.sql
  dbt/include/redshift/macros/utils/get_columns_spec_ddl.sql
  dev-requirements.txt
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#404 Repair accidental change to dev-requirements
  .changes/unreleased/Fixes-20230411-143706.yaml
  dev-requirements.txt
Labels: cla:yes

#398 fix the json obj in msgs bug for both text and Json logs
  .changes/unreleased/Fixes-20230407-213725.yaml
  dbt/adapters/redshift/connections.py
Labels: cla:yes, backport 1.3.latest

#393 update to generalize constraints
  .changes/1.5.0/Features-20221209-105640.yaml
  dbt/adapters/redshift/impl.py
Labels: cla:yes, Skip Changelog

#408 1.5.0rc1 changelog
  .changes/1.5.0-b1.md
  .changes/1.5.0-b2.md
  .changes/1.5.0-b3.md
  .changes/1.5.0-b4.md
  .changes/1.5.0-rc1.md
  .changes/1.5.0/Features-20230406-104634.yaml
  .changes/1.5.0/Fixes-20230407-213725.yaml
  .changes/1.5.0/Fixes-20230411-143706.yaml
Labels: cla:yes, Skip Changelog

#410 work towards fixing changelog for rc
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#412 revert changes to point to 1.4.latest until 1.5.final is released
  .github/workflows/nightly-release.yml
Labels: cla:yes, Skip Changelog

#414 Update pytest requirement from ~=7.2 to ~=7.3
  .changes/unreleased/Dependencies-20230421-032407.yaml
  dev-requirements.txt
Labels: cla:yes, dependencies, Skip Changelog

#420 Fix for #419: dbt-redshift 1.5 does not work with non-standard redshift hostnames
  .changes/unreleased/Fixes-20230428-142321.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes
