Repository dbt-labs/dbt-redshift, pull requests merged in 2023-02, with the labels that each got.

#288 [BACKPORT] Remove PR requirement from Changelog (#280)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#285 [BACKPORT] Remove PR requirement from Changelog (#280)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#286 [BACKPORT] Remove PR requirement from Changelog (#280)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#287 [BACKPORT] Remove PR requirement from Changelog (#280)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#304 update regex for version bump
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#306 [CT-1953]: convert redshift_test to functional test
  tests/functional/adapter/redshift_test/test_late_binding_view.py
  tests/integration/redshift_test/models/model.sql
  tests/integration/redshift_test/seed/seed.csv
  tests/integration/redshift_test/test_late_binding_view.py
Labels: cla:yes, Skip Changelog

#305 update prerelease -> prekind
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#299 [CI/CD] Backport release workflow to `1.4.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#308 init push for macro_test conversion
  tests/functional/adapter/test_macros.py
  tests/integration/macro_tests/dispatch-inheritance-models/model.sql
  tests/integration/macro_tests/models/.gitkeep
  tests/integration/macro_tests/models/dep_macro.sql
  tests/integration/macro_tests/models/local_macro.sql
  tests/integration/macro_tests/models/ref_macro.sql
  tests/integration/macro_tests/no-default-macros/my_macros.sql
  tests/integration/macro_tests/override-get-columns-macros/macros.sql
  tests/integration/macro_tests/override-get-columns-models/model.sql
  tests/integration/macro_tests/package_macro_overrides/dbt_project.yml
  tests/integration/macro_tests/package_macro_overrides/macros/macros.sql
  tests/integration/macro_tests/seed.sql
  tests/integration/macro_tests/test_macros.py
Labels: cla:yes, Skip Changelog

#298 [CI/CD] Backport release workflow to `1.3.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#301 convert test_store_test_failures to functional test
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
  tests/integration/store_test_failures_tests/models/fine_model.sql
  tests/integration/store_test_failures_tests/models/fine_model_but_with_a_no_good_very_long_name.sql
  tests/integration/store_test_failures_tests/models/problematic_model.sql
  tests/integration/store_test_failures_tests/models/schema.yml
  tests/integration/store_test_failures_tests/seeds/expected/expected_accepted_values.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_failing_test.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_not_null_problematic_model_id.csv
  tests/integration/store_test_failures_tests/seeds/expected/expected_unique_problematic_model_id.csv
  tests/integration/store_test_failures_tests/seeds/people.csv
  tests/integration/store_test_failures_tests/test_store_test_failures.py
  tests/integration/store_test_failures_tests/tests/failing_test.sql
  tests/integration/store_test_failures_tests/tests/passing_test.sql
Labels: cla:yes, Skip Changelog

#297 [CI/CD] Backport release workflow to `1.2.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, Skip Changelog

#307 Ct 1955/remove column comments tests
  tests/integration/column_comments_tests/models/quote_model.sql
  tests/integration/column_comments_tests/models/schema.yml
  tests/integration/column_comments_tests/test_column_comments.py
Labels: cla:yes, Skip Changelog

#310 [CT-2029]:Convert simple seed to a functional test
  tests/functional/adapter/test_simple_seed.py
  tests/integration/simple_seed_test/macros/schema_test.sql
  tests/integration/simple_seed_test/models-downstream-seed/model.sql
  tests/integration/simple_seed_test/models-exist/model.sql
  tests/integration/simple_seed_test/models-rs/schema.yml
  tests/integration/simple_seed_test/seed.sql
  tests/integration/simple_seed_test/seeds-config/seed_disabled.csv
  tests/integration/simple_seed_test/seeds-config/seed_enabled.csv
  tests/integration/simple_seed_test/seeds-config/seed_tricky.csv
  tests/integration/simple_seed_test/seeds/seed_actual.csv
  tests/integration/simple_seed_test/test_seed_type_override.py
Labels: cla:yes, Skip Changelog

#295 convert backup table integration tests to functional tests
  .changes/unreleased/Under the Hood-20230130-205628.yaml
  tests/functional/adapter/conftest.py
  tests/functional/adapter/test_backup_table.py
  tests/integration/backup_table_tests/models/model_backup_false.sql
  tests/integration/backup_table_tests/models/model_backup_param_before_distkey.sql
  tests/integration/backup_table_tests/models/model_backup_param_before_sortkey.sql
  tests/integration/backup_table_tests/models/model_backup_true.sql
  tests/integration/backup_table_tests/models/model_backup_true_view.sql
  tests/integration/backup_table_tests/models/model_backup_undefined.sql
  tests/integration/backup_table_tests/test_backup_table_option.py
Labels: cla:yes

#268 Rm defer_state_test
  tests/integration/defer_state_test/changed_models/ephemeral_model.sql
  tests/integration/defer_state_test/changed_models/schema.yml
  tests/integration/defer_state_test/changed_models/table_model.sql
  tests/integration/defer_state_test/changed_models/view_model.sql
  tests/integration/defer_state_test/changed_models_bad/ephemeral_model.sql
  tests/integration/defer_state_test/changed_models_bad/schema.yml
  tests/integration/defer_state_test/changed_models_bad/table_model.sql
  tests/integration/defer_state_test/changed_models_bad/view_model.sql
  tests/integration/defer_state_test/changed_models_missing/schema.yml
  tests/integration/defer_state_test/changed_models_missing/table_model.sql
  tests/integration/defer_state_test/changed_models_missing/view_model.sql
  tests/integration/defer_state_test/macros/macros.sql
  tests/integration/defer_state_test/models/ephemeral_model.sql
  tests/integration/defer_state_test/models/exposures.yml
  tests/integration/defer_state_test/models/schema.yml
  tests/integration/defer_state_test/models/table_model.sql
  tests/integration/defer_state_test/models/view_model.sql
  tests/integration/defer_state_test/seeds/seed.csv
  tests/integration/defer_state_test/snapshots/my_snapshot.sql
  tests/integration/defer_state_test/test_defer_state.py
Labels: cla:yes, Skip Changelog

#294 remove invocation of integration tests in tox
  .changes/unreleased/Under the Hood-20230130-171158.yaml
  CONTRIBUTING.md
  tox.ini
Labels: cla:yes

#313 parse vars in unit test utils
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#302 Sync Changelog team to GitHub team
  .bumpversion.cfg
  .changie.yaml
Labels: cla:yes, Skip Changelog

#251 Modify RedshiftConnectionManager to extend from SQLConnectionManager, migrate from psycopg2 to redshift python connector
  .changes/unreleased/Under the Hood-20230118-071542.yaml
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/impl.py
  setup.py
  tests/unit/test_redshift_adapter.py
Labels: ok_to_test, cla:yes, test all, ready_for_review, ok to test

#229 dbt Constraints / model contracts
  .changes/unreleased/Features-20221209-105640.yaml
  dbt/include/redshift/macros/adapters.sql
  dbt/include/redshift/macros/utils/get_columns_spec_ddl.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#321 add new workflow
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#328 fix release bugs on redshift for version and workflow (#326)
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  setup.py
Labels: cla:yes, Skip Changelog

#329 Test updating dev-requirements.txt / setup.py on workflow dispatch
  .github/scripts/update_dbt_core_branch.sh
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#336 Rename "constraints_enabled" to "contract"
  .changes/unreleased/Under the Hood-20230223-110314.yaml
  dbt/include/redshift/macros/adapters.sql
Labels: cla:yes

#337 add codeowners file
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#309 CT-1960: test conversion - simple snapshot tests
  tests/functional/adapter/common.py
  tests/functional/adapter/snapshot_tests/seeds.py
  tests/functional/adapter/snapshot_tests/snapshots.py
  tests/functional/adapter/snapshot_tests/test_snapshot.py
  tests/functional/adapter/test_column_types.py
  tests/functional/adapter/test_late_binding_view.py
  tests/functional/adapter/test_query_comment.py
  tests/functional/adapter/test_relation_name.py
  tests/functional/adapter/test_store_test_failures.py
  tests/integration/simple_snapshot_test/add_column_to_source_bq.sql
  tests/integration/simple_snapshot_test/check-snapshots-expected/check_snapshots_test_current.sql
  tests/integration/simple_snapshot_test/check-snapshots/check_cols_cycle.sql
  tests/integration/simple_snapshot_test/custom-snapshot-macros/custom.sql
  tests/integration/simple_snapshot_test/invalidate_bigquery.sql
  tests/integration/simple_snapshot_test/invalidate_postgres.sql
  tests/integration/simple_snapshot_test/invalidate_snowflake.sql
  tests/integration/simple_snapshot_test/macros/test_no_overlaps.sql
  tests/integration/simple_snapshot_test/models-collision/snapshot_actual.sql
  tests/integration/simple_snapshot_test/models-slow/gen.sql
  tests/integration/simple_snapshot_test/models/.gitkeep
  tests/integration/simple_snapshot_test/models/ref_snapshot.sql
  tests/integration/simple_snapshot_test/models/schema.yml
  tests/integration/simple_snapshot_test/seed.sql
  tests/integration/simple_snapshot_test/seed_bq.sql
  tests/integration/simple_snapshot_test/seed_longtext.sql
  tests/integration/simple_snapshot_test/seed_pg.sql
  tests/integration/simple_snapshot_test/seeds/seed.csv
  tests/integration/simple_snapshot_test/seeds/seed_newcol.csv
  tests/integration/simple_snapshot_test/test-check-col-snapshots-bq/snapshot.sql
  tests/integration/simple_snapshot_test/test-check-col-snapshots-noconfig/snapshot.sql
  tests/integration/simple_snapshot_test/test-check-col-snapshots/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-bq/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-changing-strategy-tests/test_snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-changing-strategy/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-checkall/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-invalid/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-longtext/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-pg-custom-invalid/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-pg-custom-namespaced/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-pg-custom/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-pg/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-select-noconfig/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-select/snapshot.sql
  tests/integration/simple_snapshot_test/test-snapshots-slow-tests/test_timestamps.sql
  tests/integration/simple_snapshot_test/test-snapshots-slow/snapshot.sql
  tests/integration/simple_snapshot_test/test_simple_snapshot.py
  tests/integration/simple_snapshot_test/test_snapshot_check_cols.py
  tests/integration/simple_snapshot_test/update.sql
  tests/integration/simple_snapshot_test/update_bq.sql
Labels: cla:yes, Skip Changelog

#322 mirror issues to ADAP jira project
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog

#338 Revert "mirror issues to ADAP jira project"
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes
