Repository dbt-labs/dbt-redshift, pull requests merged in 2024-06, with the labels that each got.

#833 [Backport 1.7.latest] Fix macos runner typo (#820)
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#834 [Backport 1.6.latest] Fix macos runner typo (#820)
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#831 Adap 746/merge agate lazy load
  .changes/unreleased/Under the Hood-20240331-103115.yaml
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/impl.py
  dbt/adapters/redshift/relation_configs/base.py
  dbt/adapters/redshift/relation_configs/dist.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/sort.py
Labels: cla:yes

#844 Pin to 2.1.1 and below to fix the cursor error.
  .changes/unreleased/Fixes-20240612-131752.yaml
  setup.py
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#836 Remove group_federation for serverless
  .changes/unreleased/Fixes-20240531-113620.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_auth_method.py
Labels: cla:yes

#847 update user docs-issue workflow
  .github/workflows/docs-issues.yml
Labels: cla:yes, Skip Changelog

#849 Update internal release naming and arguments
  .github/workflows/release-internal.yml
Labels: cla:yes, Skip Changelog

#850 remove calculated version for dbt-postgres dependency
  setup.py
Labels: cla:yes, Skip Changelog
