Repository dbt-labs/dbt-redshift, pull requests merged in 2024-05, with the labels that each got.

#782 Stop adding aliases to render_limited output
  .changes/unreleased/Fixes-20240423-131503.yaml
  dbt/adapters/redshift/relation.py
  tests/functional/adapter/empty/test_empty.py
Labels: cla:yes

#812 Update dev-requirements.txt to point to 1.8.latest
  dev-requirements.txt
Labels: Skip Changelog

#814 Add missing changelog backlinks.
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#774 Add integration tests for IAM User auth
  .changes/unreleased/Features-20240419-145208.yaml
  dbt/adapters/redshift/connections.py
  test.env.example
  tests/conftest.py
  tests/functional/conftest.py
  tests/functional/test_auth_method.py
  tests/unit/mock_adapter.py
  tests/unit/test_auth_method.py
  tests/unit/test_connection.py
  tests/unit/test_conversion.py
  tests/unit/test_materialized_view.py
  tests/unit/test_query.py
  tests/unit/test_redshift_adapter.py
  tests/unit/test_relation.py
  tests/unit/test_ssl_mode.py
  tests/unit/utils.py
Labels: cla:yes

#815 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#797 [Backport 1.7.latest] Move to `pre-commit` only (#777)
  .flake8
  .github/workflows/main.yml
  .pre-commit-config.yaml
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/relation_configs/dist.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/sort.py
  dev-requirements.txt
  mypy.ini
  tests/unit/relation_configs/test_materialized_view.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#798 [Backport 1.6.latest] Move to `pre-commit` only (#777)
  .flake8
  .github/workflows/main.yml
  .pre-commit-config.yaml
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/relation_configs/dist.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/sort.py
  dev-requirements.txt
  mypy.ini
  tests/unit/relation_configs/test_materialized_view.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#813 Mark flaky tests
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  pytest.ini
  tests/conftest.py
  tests/functional/adapter/catalog_tests/test_get_catalog.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/functional/adapter/test_basic.py
  tests/functional/adapter/test_persist_docs.py
  tox.ini
Labels: cla:yes, Skip Changelog

#820 Fix macos runner typo
  .github/workflows/integration.yml
Labels: Skip Changelog

#806 Cross-database `date` macro
  .changes/unreleased/Features-20240501-151859.yaml
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#805 Import relevant pytest(s) for cross-database `cast` macro
  .changes/unreleased/Features-20240430-185708.yaml
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#825 [Backport 1.8.latest] Mark flaky tests (#813)
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  pytest.ini
  tests/conftest.py
  tests/functional/adapter/catalog_tests/test_get_catalog.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/functional/adapter/test_basic.py
  tests/functional/adapter/test_persist_docs.py
  tox.ini
Labels: cla:yes, Skip Changelog

#826 [Backport 1.7.latest] Mark flaky tests (#813)
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  pytest.ini
  tests/conftest.py
  tests/functional/adapter/catalog_tests/test_get_catalog.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/functional/adapter/test_basic.py
  tests/functional/adapter/test_persist_docs.py
  tox.ini
Labels: cla:yes, Skip Changelog

#827 [Backport 1.6.latest] Mark flaky tests (#813)
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  pytest.ini
  tests/conftest.py
  tests/functional/adapter/catalog_tests/test_relation_types.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  tests/functional/adapter/test_basic.py
  tests/functional/adapter/test_persist_docs.py
  tox.ini
Labels: cla:yes, Skip Changelog

#758 Add docker release to the full release process for final releases
  .github/dependabot.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release-prep.yml
  .github/workflows/release.yml
  Makefile
  docker/Dockerfile
  docker/README.md
  docker/dev.Dockerfile
Labels: cla:yes, Skip Changelog

#829 Add aws cli setup to the internal PyPI release pipeline
  .github/workflows/release-internal.yml
Labels: bug, cla:yes, Skip Changelog
