Repository dbt-labs/dbt-redshift, pull requests merged in 2024-04, with the labels that each got.

#751 [Backport 1.3.latest] Test ddtrace dependency range (#733)
  .changes/unreleased/Dependencies-20240319-101832.yaml
  dev-requirements.txt
Labels: cla:yes

#752 [Backport 1.2.latest] Test ddtrace dependency range (#733)
  .changes/unreleased/Dependencies-20240319-101832.yaml
  dev-requirements.txt
Labels: cla:yes

#756 Add `dbt-core~=1.8.0a1` as convenience dep
  .changes/unreleased/Dependencies-20240403-134607.yaml
  setup.py
  tests/functional/adapter/test_query_comment.py
Labels: cla:yes

#759 Update dependabot config to cover GHA
  .changes/unreleased/Under the Hood-20240410-182912.yaml
  .github/dependabot.yml
Labels: cla:yes

#718 Allow dbt to cancel connections
  .changes/unreleased/Fixes-20240326-123703.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes, ok to test, backport 1.7.latest

#767 [Backport 1.7.latest] Allow dbt to cancel connections
  .changes/unreleased/Fixes-20240326-123703.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_redshift_adapter.py
Labels: cla:yes

#768 update sqlparse to be in line with dbt-core
  .changes/unreleased/Security-20240416-195919.yaml
  setup.py
Labels: cla:yes

#744 TableLastModifiedMetadataBatch capability
  .changes/unreleased/Features-20240404-171441.yaml
  dbt/adapters/redshift/impl.py
  tests/functional/adapter/sources_freshness_tests/test_get_relation_last_modified.py
Labels: cla:yes

#775 Add pre-commit check for dbt-core
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog

#777 Move to `pre-commit` only
  .flake8
  .github/workflows/main.yml
  .pre-commit-config.yaml
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/relation_configs/dist.py
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/sort.py
  dev-requirements.txt
  mypy.ini
  tests/unit/relation_configs/test_materialized_view.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#783 Make space for both user and role in testing, add role environment variables
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#784 Add `REDSHIFT_TEST_REGION` to CI env
  .github/workflows/integration.yml
Labels: cla:yes

#786 Update workflow to support iam user and iam role tests
  .github/workflows/integration.yml
Labels: cla:yes

#787 Pin `macos` test runners to `macos-12`
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#794 [Backport 1.1.latest] Pin `macos` runners to `macos-12` (#787)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#793 [Backport 1.2.latest] Pin `macos` runners to `macos-12` (#787)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#792 [Backport 1.3.latest] Pin `macos` runners to `macos-12` (#787)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#789 [Backport 1.6.latest] Pin `macos` runners to `macos-12` (#787)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#788 [Backport 1.7.latest] Pin `macos` runners to `macos-12` (#787)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#791 [Backport 1.4.latest] Pin `macos` runners to `macos-12` (#787)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#790 [Backport 1.5.latest] Pin `macos` runners to `macos-12` (#787)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog
