Repository dbt-labs/dbt-redshift, pull requests merged in 2024-03, with the labels that each got.

#727 allow for pre-release common/adapters
  setup.py
Labels: cla:yes, Skip Changelog

#728 Add explicit dependency on sqlparse that used to inherit from core
  .github/workflows/main.yml
  .github/workflows/release.yml
  setup.py
Labels: cla:yes, Skip Changelog

#732 Add Redshift internal build process workflow
  .changes/unreleased/Features-20240318-030018.yaml
  .github/workflows/release-internal.yml
  setup.py
Labels: cla:yes

#733 Test ddtrace dependency range
  .changes/unreleased/Dependencies-20240319-101832.yaml
  dev-requirements.txt
Labels: cla:yes

#731 [Bug] Python driver 2.0.918 causes SSL error. Need to revert back to 2.0.917
  .changes/unreleased/Fixes-20240317-113447.yaml
  setup.py
Labels: cla:yes, backport 1.7.latest

#737 [Backport 1.7.latest] Fix the renamed relations code
  .changes/unreleased/Under the Hood-20240227-002713.yaml
  dbt/adapters/redshift/relation.py
  dbt/include/redshift/macros/relations/materialized_view/create.sql
  dbt/include/redshift/macros/relations/view/rename.sql
  dbt/include/redshift/macros/relations/view/replace.sql
  tests/unit/test_renamed_relations.py
Labels: cla:yes

#735 Finish internal build workflow
  .github/workflows/release-internal.yml
Labels: cla:yes, Skip Changelog

#743 Pin `black>=24.3`
  .changes/unreleased/Security-20240327-191927.yaml
  dev-requirements.txt
Labels: cla:yes
