Repository dbt-labs/dbt-redshift, pull requests merged in 2024-02, with the labels that each got.

#709 fix redshift dev reqs
  dev-requirements.txt
  tests/functional/adapter/test_query_comment.py
Labels: cla:yes, Skip Changelog

#703 loosen redshift-connector dependency <=2.0.918, >=2.0.913
  .changes/unreleased/Dependencies-20240118-095025.yaml
  setup.py
Labels: cla:yes

#711 [Bug] Initialize sqlparse lexer prior to using sqlparse
  .changes/unreleased/Fixes-20240206-132326.yaml
  dbt/adapters/redshift/connections.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest, backport 1.7.latest

#715 Remove actions that sync github and jira
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog, support

#680 [Redshift] Add tests for unit testing
  dev-requirements.txt
  setup.py
  tests/functional/adapter/unit_testing/test_unit_testing.py
Labels: cla:yes, Skip Changelog

#692 Implement relation filtering on get_catalog macro
  .changes/unreleased/Features-20231214-195655.yaml
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/catalog.sql
  dbt/include/redshift/macros/catalog/by_relation.sql
  dbt/include/redshift/macros/catalog/by_schema.sql
  dbt/include/redshift/macros/catalog/catalog.sql
  tests/functional/adapter/catalog_tests/test_get_catalog.py
  tests/functional/adapter/materialized_view_tests/test_materialized_views.py
Labels: cla:yes, backport 1.7.latest

#694 Implementation of metadata-based freshness
  .changes/unreleased/Features-20231219-120533.yaml
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/metadata/relation_last_modified.sql
  dev-requirements.txt
  tests/functional/adapter/sources_freshness_tests/files.py
  tests/functional/adapter/sources_freshness_tests/test_get_relation_last_modified.py
Labels: cla:yes, backport 1.7.latest

#721 [Backport 1.7.latest] Implementation of metadata-based freshness
  .changes/unreleased/Features-20231219-120533.yaml
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/metadata/relation_last_modified.sql
  tests/functional/adapter/sources_freshness_tests/files.py
  tests/functional/adapter/sources_freshness_tests/test_get_relation_last_modified.py
Labels: cla:yes

#725 update dbt-common dependency to <2.0
  setup.py
Labels: cla:yes, Skip Changelog

#720 [Backport 1.7.latest] Implement relation filtering on get_catalog macro
  .changes/unreleased/Features-20231214-195655.yaml
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/catalog.sql
  dbt/include/redshift/macros/catalog/by_relation.sql
  dbt/include/redshift/macros/catalog/by_schema.sql
  dbt/include/redshift/macros/catalog/catalog.sql
  tests/functional/adapter/catalog_tests/test_get_catalog.py
Labels: cla:yes
