Repository dbt-labs/dbt-redshift, pull requests merged in 2024-08, with the labels that each got.

#889 Integration workflow update to support all-in-one adapter testing
  .github/scripts/update_dbt_core_branch.sh
  .github/scripts/update_dev_dependency_branches.sh
  .github/workflows/integration.yml
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#893 Remove 1.8.latest core reference from install.
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#853 Correct syntax for mv comments
  .changes/unreleased/Fixes-20240715-143507.yaml
  dbt/include/redshift/macros/adapters.sql
  tests/functional/adapter/test_persist_docs.py
Labels: cla:yes, community

#841 Fix config change detection not working for multiple sortkey in materialized views
  .changes/unreleased/Fixes-20240610-104114.yaml
  dbt/adapters/redshift/relation_configs/materialized_view.py
  dbt/adapters/redshift/relation_configs/sort.py
  dbt/include/redshift/macros/relations/materialized_view/describe.sql
  tests/unit/test_materialized_view.py
  tests/unit/test_relation.py
Labels: cla:yes, ok to test, community
