Repository dbt-labs/dbt-redshift, pull requests merged in 2024-11, with the labels that each got.

#940 Remove `get_columns` implementation for column metadata generation
  .changes/unreleased/Fixes-20241101-150335.yaml
  dbt/adapters/redshift/connections.py
  dbt/adapters/redshift/impl.py
  tests/functional/test_columns_in_relation.py
Labels: cla:yes

#895 add InterfaceError to retryable_exceptions
  .changes/unreleased/Fixes-20240806-163017.yaml
  dbt/adapters/redshift/connections.py
  tests/unit/test_connection.py
Labels: cla:yes

#942 Test `macos-14` on Python 3.10 instead of Python 3.9 due to missing `psycopg2-binary`
  .github/workflows/integration.yml
Labels: cla:yes, Skip Changelog

#943 Fix integration test matrix
  .github/workflows/integration.yml
Labels: Skip Changelog

#924 Add microbatch strategy
  .changes/unreleased/Features-20241002-171112.yaml
  dbt/adapters/redshift/impl.py
  dbt/include/redshift/macros/materializations/incremental_merge.sql
  tests/functional/adapter/incremental/test_incremental_microbatch.py
Labels: cla:yes

#945 move github runner from macos-12 to macos-14 (#941, #942, #943)
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#947 move github runner from macos-12 to macos-14 (#941, #942, #943)
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#948 move github runner from macos-12 to macos-14 (#941, #942, #943)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#949 move github runner from macos-12 to macos-14 (#941, #942, #943)
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#954 Fix macos14 tests on 1.5
  .github/scripts/integration-test-matrix.js
Labels: cla:yes, Skip Changelog

#953 Update the macos14 python version
  .github/scripts/integration-test-matrix.js
Labels: cla:yes, Skip Changelog

#950 Add browser IDC authentication method
  .changes/unreleased/Features-20241122-143326.yaml
  dbt/adapters/redshift/connections.py
  setup.py
  tests/unit/test_auth_method.py
Labels: cla:yes
