Repository dbt-labs/dbt-redshift, pull requests merged in 2025-01, with the labels that each got.

#972 Update release-internal.yml to use hatch
  .github/workflows/release-internal.yml
Labels: cla:yes, Skip Changelog

#970 Add Redshift Iam Idc token authentication method with an eye towards future supported Idps
  .changes/unreleased/Features-20241217-181340.yaml
  dbt/adapters/redshift/auth_providers.py
  dbt/adapters/redshift/connections.py
  hatch.toml
  pyproject.toml
  tests/functional/test_auth_method.py
  tests/unit/test_auth_method.py
Labels: cla:yes

#977 Remove the artifacts related workflow steps
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#978 Remove artifacts workflows 1.6
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#979 Remove the artifacts related workflow steps
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#980 Remove the artifacts related workflow steps
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#981 Remove the artifacts related workflow steps
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: cla:yes

#982 Remove the artifacts related workflow steps
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#984 ADAP-1135: Update dbt-adapters ref for monorepo subdirectory
  dev-requirements.txt
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#986 [Backport 1.9.latest] Combine the build and check build jobs into one job
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#987 [Backport 1.8.latest] Combine build and check build jobs into one job
  .github/workflows/main.yml
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#988 [Backport 1.7.latest] Combine build and build check jobs into one job
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#989 [Backport 1.6.latest] Combine the build and check build jobs into one job
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#990 [Backport 1.5.latest] Combine the build and check build jobs into one job
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#991 [Backport 1.4.latest] Combine the build and check build jobs into one job
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog
